version: '3.8'

services:
  sentuh-tanahku-llm:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./sentuh_tanahku_model:/app/sentuh_tanahku_model
      - ./processed_knowledge.json:/app/processed_knowledge.json
      - ./training_data.jsonl:/app/training_data.jsonl
    environment:
      - PYTHONPATH=/app
      - TOKENIZERS_PARALLELISM=false
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Add monitoring
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  portainer_data: