services:
  sentuh-tanahku-api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8000:8000"
    volumes:
      - ./data/embeddings:/app/data/embeddings
      - ./config:/app/config
      - ./data/csv:/app/data/csv
    environment:
      - PYTHONPATH=/app
      - TOKENIZERS_PARALLELISM=false
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sentuh_tanahku
      - DB_USER=postgres
      - DB_PASSWORD=postgres123
      - DB_SSL_MODE=prefer
      - DB_CONNECTION_TIMEOUT=30
    depends_on:
      - postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=sentuh_tanahku
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5433:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Add monitoring
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  portainer_data: